do a check before installing vundle or homebrew. better output

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,21 +1,40 @@
+#!/bin/bash
+
 # a basic setup script for starting up a new mac
 
-# install homebrew
-/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"/
+echo "looking for homebrew"
+which -s brew
+if [[ $? != 0  ]] ; then
+    echo "installing homebrew";
+    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+else
+    echo "updating homebrew"    
+    brew update
+fi
 
 # install vundle
-git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim;
+echo "looking for vundle";
+if [ ! -d $HOME/.vim/bundle/Vundle.vim ]; then
+    echo "installing vundle"
+    git clone -q https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim;
+else
+    echo "vundle already installed"
+fi
 
 # TODO: add a thing if dotpath doesnt exit - bail now. echo you gotta source the bashrc
 
 # create top-level files
+echo "creating any missing dotfiles"
 if [ ! -f $HOME/.tmux.conf ]; then
+    echo "adding .tmux.conf"
     echo "source-file $DOTPATH/.tmux.conf" > $HOME/.tmux.conf
 fi
 if [ ! -f $HOME/.bash_profile ]; then
+    echo "adding .bash_profile"
     echo "source $DOTPATH/.bashrc" > $HOME/.bash_profile
 fi
 if [ ! -f $HOME/.vimrc ]; then
+    echo "adding .vimrc"
     echo "source $DOTPATH/.bashrc" > $HOME/.vimrc
 fi
 
